// <auto-generated />
using System;
using LucidCartographer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LucidCartographer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260426192607_AddEnrichmentNeedsManualUrl")]
    partial class AddEnrichmentNeedsManualUrl
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.12");

            modelBuilder.Entity("LucidCartographer.Data.Entities.Poi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("AddedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Address")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("EnrichmentFailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("EnrichmentNeedsManualUrl")
                        .HasColumnType("INTEGER");

                    b.Property<string>("GoogleMapsUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<double?>("GoogleRating")
                        .HasColumnType("REAL");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnriched")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastEnrichmentAttemptAt")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasMaxLength(10000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Region")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ReviewCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("VisitedDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Website")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GoogleMapsUrl");

                    b.HasIndex("IsEnriched");

                    b.HasIndex("Name");

                    b.HasIndex("Status");

                    b.HasIndex("Latitude", "Longitude");

                    b.HasIndex("IsEnriched", "EnrichmentFailureCount", "LastEnrichmentAttemptAt");

                    b.ToTable("Pois", t =>
                        {
                            t.HasCheckConstraint("CK_Poi_EnrichmentFailureCount", "EnrichmentFailureCount >= 0");

                            t.HasCheckConstraint("CK_Poi_GoogleRating", "GoogleRating IS NULL OR (GoogleRating >= 1.0 AND GoogleRating <= 5.0)");

                            t.HasCheckConstraint("CK_Poi_Latitude", "Latitude IS NULL OR (Latitude >= -90 AND Latitude <= 90)");

                            t.HasCheckConstraint("CK_Poi_Longitude", "Longitude IS NULL OR (Longitude >= -180 AND Longitude <= 180)");

                            t.HasCheckConstraint("CK_Poi_Rating", "Rating IS NULL OR (Rating >= 1 AND Rating <= 5)");

                            t.HasCheckConstraint("CK_Poi_ReviewCount", "ReviewCount IS NULL OR ReviewCount >= 0");
                        });
                });

            modelBuilder.Entity("LucidCartographer.Data.Entities.PoiCollection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("IconName")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceFileName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("SourceType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("PoiCollections");
                });

            modelBuilder.Entity("LucidCartographer.Data.Entities.PoiCollectionItem", b =>
                {
                    b.Property<int>("PoiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PoiCollectionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PoiId", "PoiCollectionId");

                    b.HasIndex("PoiCollectionId");

                    b.ToTable("PoiCollectionItems");
                });

            modelBuilder.Entity("LucidCartographer.Data.Entities.PoiImage", b =>
                {
                    b.Property<int>("PoiId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentType")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.HasKey("PoiId");

                    b.ToTable("PoiImages");
                });

            modelBuilder.Entity("LucidCartographer.Data.Entities.PoiTag", b =>
                {
                    b.Property<int>("PoiId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TagId")
                        .HasColumnType("INTEGER");

                    b.HasKey("PoiId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("PoiTags");
                });

            modelBuilder.Entity("LucidCartographer.Data.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("LucidCartographer.Data.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("LucidCartographer.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LucidCartographer.Data.Entities.PoiCollectionItem", b =>
                {
                    b.HasOne("LucidCartographer.Data.Entities.PoiCollection", "PoiCollection")
                        .WithMany("CollectionItems")
                        .HasForeignKey("PoiCollectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LucidCartographer.Data.Entities.Poi", "Poi")
                        .WithMany("CollectionItems")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");

                    b.Navigation("PoiCollection");
                });

            modelBuilder.Entity("LucidCartographer.Data.Entities.PoiImage", b =>
                {
                    b.HasOne("LucidCartographer.Data.Entities.Poi", "Poi")
                        .WithOne("Image")
                        .HasForeignKey("LucidCartographer.Data.Entities.PoiImage", "PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");
                });

            modelBuilder.Entity("LucidCartographer.Data.Entities.PoiTag", b =>
                {
                    b.HasOne("LucidCartographer.Data.Entities.Poi", "Poi")
                        .WithMany("PoiTags")
                        .HasForeignKey("PoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LucidCartographer.Data.Entities.Tag", "Tag")
                        .WithMany("PoiTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poi");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("LucidCartographer.Data.Entities.Poi", b =>
                {
                    b.Navigation("CollectionItems");

                    b.Navigation("Image");

                    b.Navigation("PoiTags");
                });

            modelBuilder.Entity("LucidCartographer.Data.Entities.PoiCollection", b =>
                {
                    b.Navigation("CollectionItems");
                });

            modelBuilder.Entity("LucidCartographer.Data.Entities.Tag", b =>
                {
                    b.Navigation("PoiTags");
                });
#pragma warning restore 612, 618
        }
    }
}
